# Generated by Django 3.0.3 on 2020-03-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(max_length=70, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=70, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=40, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='zip_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Zip code'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=70, null=True, verbose_name='Position')),
                ('organization_name', models.CharField(max_length=70, null=True, verbose_name='Organization')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('resume_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=70, null=True, verbose_name='Organization')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('resume_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
    ]
