# Generated by Django 3.0.3 on 2020-03-10 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200306_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(max_length=70, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
