# Generated by Django 3.0.3 on 2020-04-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200312_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Zip code'),
        ),
    ]
